export enum BiddingFormState {
    BEFORE_AUCTION_START = 'BEFORE_AUCTION_START',
    BEFORE_ROUND_START = 'BEFORE_ROUND_START',
    BEFORE_YOUR_TURN_START = 'BEFORE_YOUR_TURN_START',
    ACTIVE_BIDDING_TIME = 'ACTIVE_BIDDING_TIME',
    BIDDING_TIME_END = 'BIDDING_TIME_END',
}
